Chapter12/Exercise12.02/citireview/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'home#index'

resources :reviews do
  resources :comments
end

end

Chapter12/Exercise12.02/citireview/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  validates :body, length: { maximum: 50 }
end

Chapter12/Exercise12.02/citireview/app/models/review.rb
class Review < ApplicationRecord
    has_many :comments   
    validates :name, presence: true
end

Chapter12/Exercise12.02/citireview/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Chapter12/Exercise12.02/citireview/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @review = Review.find(params[:review_id])
        @comment = @review.comments.create(comment_params)
        redirect_to review_path(@review)
      end
     
    private
        def comment_params
          params.require(:comment).permit(:commenter, :body)
    end

end

Chapter12/Exercise12.02/citireview/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

Chapter12/Exercise12.02/citireview/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!

    def index
        @reviews = Review.all
    end

    def show
        @review = Review.find(params[:id])
    end

    def new 
    end

    def create
        parameters = params[:review]
        @review = Review.new(name: parameters[:name], description: parameters[:description])

        @review.save
        redirect_to @review
    end

    private
    def relationship_params
        params.require(:review).permit(:name, :description)
    end
end

Chapter12/Exercise12.02/citireview/app/helpers/comments_helper.rb
module CommentsHelper
end

Chapter12/Exercise12.02/citireview/app/views/home/index.html.erb
<h1>Welcome to Citireviews</h1>
<%= link_to 'All Reviews', controller: 'reviews' %> <br/><br/>
<%= link_to 'Add new review', new_review_path %>

Chapter12/Exercise12.02/citireview/app/views/reviews/index.html.erb
<h1>All the Reviews</h1>
 
<table>
  <tr>
    <th>Sno</th>
    <th>Name</th>
    <th></th>
  </tr>
 
  <% @reviews.each_with_index do |review, index| %>
    <tr>
      <td><%= index+1 %></td>
      <td><%= review.name %></td>
      <td><%= link_to 'Details', review_path(review) %></td>
    </tr>
  <% end %>
</table>
<br/>

<%= link_to 'Back', root_path %>

Chapter12/Exercise12.02/citireview/app/views/reviews/new.html.erb
<h1>Add new review</h1>


<%= form_with scope: :review, url: reviews_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', root_path %>

Chapter12/Exercise12.02/citireview/app/views/reviews/show.html.erb
<h1>Citireviews Review for </h1>
<p>
  <strong>Name:</strong>
  <%= @review.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @review.description %>
</p>
<br/>
<strong><i>Comments for this review:</i></strong>
<% @review.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Write your comment:</h2>
<%= form_with(model: [ @review, @review.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>